#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx10240M
kotlin.native.jvmArgs=-Xmx12288M
kotlin.mpp.enableCInteropCommonization=true

#Gradle
org.gradle.jvmargs=-Xmx12288M -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=2048m
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
