#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2G
kotlin.native.jvmArgs=-Xmx5G
kotlin.mpp.enableCInteropCommonization=true

#Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=1024m
org.gradle.configuration-cache=true
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
